# Generated by Django 5.1.3 on 2024-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableinfo',
            old_name='broker_connetion',
            new_name='broker_connection',
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
