# Generated by Django 5.1.3 on 2024-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_rename_broker_connetion_tableinfo_broker_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='brokerconnection',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
