# Generated by Django 5.1.3 on 2024-12-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_dynamictable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictable',
            name='user',
        ),
    ]
